spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cclemon-auth?allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

codegen:
  types: controller,dto,entity,repository,service,specification